# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_internal/proto/common/retained_user.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0schema_internal/proto/common/retained_user.proto\x12\x06\x63ommon\"\xb5\x01\n\x0cRetainedUser\x12\x13\n\x0bplatform_id\x18\x01 \x01(\x04\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x18\n\x10retained_user_id\x18\x03 \x01(\t\x12$\n\x1c\x63reate_event_api_time_millis\x18\x04 \x01(\x04\x12\x1b\n\x13process_time_millis\x18\x05 \x01(\x04\x12\"\n\x1alast_forgotten_time_millis\x18\x06 \x01(\x04\"\x93\x01\n\x14\x41nonUserRetainedUser\x12\x13\n\x0bplatform_id\x18\x01 \x01(\x04\x12\x14\n\x0c\x61non_user_id\x18\x02 \x01(\t\x12\x18\n\x10retained_user_id\x18\x03 \x01(\t\x12\x19\n\x11\x65vent_time_millis\x18\x04 \x01(\x04\x12\x1b\n\x13process_time_millis\x18\x05 \x01(\x04\x42o\n\x18\x61i.promoted.proto.commonP\x01Z?github.com/promotedai/schema/generated/go/proto/common\xaa\x02\x0fPromoted.Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_internal.proto.common.retained_user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030ai.promoted.proto.commonP\001Z?github.com/promotedai/schema/generated/go/proto/common\252\002\017Promoted.Common'
  _globals['_RETAINEDUSER']._serialized_start=61
  _globals['_RETAINEDUSER']._serialized_end=242
  _globals['_ANONUSERRETAINEDUSER']._serialized_start=245
  _globals['_ANONUSERRETAINEDUSER']._serialized_end=392
# @@protoc_insertion_point(module_scope)
