# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_internal/proto/delivery/delivery_grpc.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema_internal.proto.delivery import delivery_pb2 as schema__internal_dot_proto_dot_delivery_dot_delivery__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2schema_internal/proto/delivery/delivery_grpc.proto\x12\rdelivery_grpc\x1a-schema_internal/proto/delivery/delivery.proto2>\n\x08\x44\x65livery\x12\x32\n\x07\x44\x65liver\x12\x11.delivery.Request\x1a\x12.delivery.Response\"\x00\x42\x97\x01\n\x1f\x61i.promoted.proto.delivery.grpcB\x12\x44\x65liveryGrpcProtosP\x01ZFgithub.com/promotedai/schema/generated/go/proto/delivery/grpc\xaa\x02\x15Promoted.DeliveryGrpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_internal.proto.delivery.delivery_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037ai.promoted.proto.delivery.grpcB\022DeliveryGrpcProtosP\001ZFgithub.com/promotedai/schema/generated/go/proto/delivery/grpc\252\002\025Promoted.DeliveryGrpc'
  _globals['_DELIVERY']._serialized_start=116
  _globals['_DELIVERY']._serialized_end=178
# @@protoc_insertion_point(module_scope)
