# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_internal/proto/delivery/inference.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.schema_internal/proto/delivery/inference.proto\x12\tinference\x1a\x1bgoogle/protobuf/empty.proto\"$\n\x12ListModelsResponse\x12\x0e\n\x06models\x18\x01 \x03(\t\"+\n\x0c\x45mbedRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\"\n\rEmbedResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x32\x91\x01\n\nEmbeddings\x12\x45\n\nListModels\x12\x16.google.protobuf.Empty\x1a\x1d.inference.ListModelsResponse\"\x00\x12<\n\x05\x45mbed\x12\x17.inference.EmbedRequest\x1a\x18.inference.EmbedResponse\"\x00\x42\x87\x01\n\x1b\x61i.promoted.proto.inferenceB\x0eInferenceProtoP\x01ZAgithub.com/promotedai/schema/generated/go/proto/delivery\xaa\x02\x12Promoted.Inferenceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_internal.proto.delivery.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033ai.promoted.proto.inferenceB\016InferenceProtoP\001ZAgithub.com/promotedai/schema/generated/go/proto/delivery\252\002\022Promoted.Inference'
  _globals['_LISTMODELSRESPONSE']._serialized_start=90
  _globals['_LISTMODELSRESPONSE']._serialized_end=126
  _globals['_EMBEDREQUEST']._serialized_start=128
  _globals['_EMBEDREQUEST']._serialized_end=171
  _globals['_EMBEDRESPONSE']._serialized_start=173
  _globals['_EMBEDRESPONSE']._serialized_end=207
  _globals['_EMBEDDINGS']._serialized_start=210
  _globals['_EMBEDDINGS']._serialized_end=355
# @@protoc_insertion_point(module_scope)
