# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_internal/proto/delivery/pacing.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+schema_internal/proto/delivery/pacing.proto\x12\x06pacing\"?\n\x0eIterateRequest\x12-\n\x07records\x18\x01 \x03(\x0b\x32\x1c.pacing.IterateRequestRecord\"M\n\x14IterateRequestRecord\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08setpoint\x18\x02 \x01(\x01\x12\x16\n\x0emeasured_value\x18\x03 \x01(\x01\"g\n\x0fIterateResponse\x12\x13\n\x0bmultipliers\x18\x01 \x03(\x01\x12\r\n\x05\x65rror\x18\x02 \x03(\x01\x12\x13\n\x0b\x64\x65lta_error\x18\x03 \x03(\x01\x12\x1b\n\x13\x64\x65lta_rolling_error\x18\x04 \x03(\x01\"\x98\x01\n\tPacingLog\x12\x0b\n\x03key\x18\x01 \x03(\t\x12\x10\n\x08setpoint\x18\x02 \x03(\x02\x12\x16\n\x0emeasured_value\x18\x03 \x03(\x02\x12\x13\n\x0bmultipliers\x18\x04 \x03(\x02\x12\r\n\x05\x65rror\x18\x05 \x03(\x02\x12\x13\n\x0b\x64\x65lta_error\x18\x06 \x03(\x02\x12\x1b\n\x13\x64\x65lta_rolling_error\x18\x07 \x03(\x02\"`\n\x15PacingControllerState\x12\x1b\n\x13last_updated_millis\x18\x01 \x01(\x03\x12\x16\n\x0eprevious_error\x18\x02 \x01(\x01\x12\x12\n\nmultiplier\x18\x03 \x01(\x01\x32\x46\n\x06Pacing\x12<\n\x07Iterate\x12\x16.pacing.IterateRequest\x1a\x17.pacing.IterateResponse\"\x00\x42~\n\x18\x61i.promoted.proto.pacingB\x0bPacingProtoP\x01ZAgithub.com/promotedai/schema/generated/go/proto/delivery\xaa\x02\x0fPromoted.Pacingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_internal.proto.delivery.pacing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030ai.promoted.proto.pacingB\013PacingProtoP\001ZAgithub.com/promotedai/schema/generated/go/proto/delivery\252\002\017Promoted.Pacing'
  _globals['_ITERATEREQUEST']._serialized_start=55
  _globals['_ITERATEREQUEST']._serialized_end=118
  _globals['_ITERATEREQUESTRECORD']._serialized_start=120
  _globals['_ITERATEREQUESTRECORD']._serialized_end=197
  _globals['_ITERATERESPONSE']._serialized_start=199
  _globals['_ITERATERESPONSE']._serialized_end=302
  _globals['_PACINGLOG']._serialized_start=305
  _globals['_PACINGLOG']._serialized_end=457
  _globals['_PACINGCONTROLLERSTATE']._serialized_start=459
  _globals['_PACINGCONTROLLERSTATE']._serialized_end=555
  _globals['_PACING']._serialized_start=557
  _globals['_PACING']._serialized_end=627
# @@protoc_insertion_point(module_scope)
