on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
      - master
      - "release/**"
      - "hotfix/**"
  pull_request:
    branches:
      - develop
      - main
      - master
      - "release/**"
      - "hotfix/**"

name: Build protos

jobs:
  build:
    name: Build
    # TODO - how to handle forks?
    # if: github.event.pull_request.head.repo.full_name == github.repository

    # This has bazelisk already
    runs-on: ubuntu-latest
    steps:

      - name: Cache Bazel
        uses: actions/cache@v2.1.6
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          # To write a new cache, we need to have a unique key.
          # TODO - try to get "-${{ hashFiles('WORKSPACE', '**/BUILD.bazel') }}"" to work
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          # We use restore-keys to find a recent cache to reuse.
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Schema repo checkout
        id: schema_repo_checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup SSH Keys and known_hosts
        id: setup_ssh_keys
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PUBLIC_REPO_SSH_PRIVATE_KEY }}"

      - name: Build protos
        id: build_protos
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          bazel sync --configure
          bazel build ...

      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      # Needed for the generate-go script.
      - name: Install Go
        id: install_go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Generate Python and Golang library
        # Generate Python library on both push and pull_requests
        id: generate_py_and_golang
        run: |
          ./generate-python.internal.sh -s || exit 1
          ./generate-go.internal.sh -s || exit 1
          git remote set-url origin https://x-access-token:${{ secrets.PROMOTED_PUBLIC_DEPLOYER_GITHUB_ACTIONS }}@github.com/${{ github.repository }}
          git config user.name prm-deployer
          git config user.email prm-deployer@promoted.ai
          git add .

      - name: Check for modified files
        id: git-check
        run: |
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
          echo $(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Commit generated Python library
        # Only commit if there is a change.
        id: commit_generated_py
        # Check if the PR is not from a fork
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git commit -m "Generate Python Library"
          git push
